export const mockRegions = [
  { id: "r1", name: "North West", code: "NW" },
  { id: "r2", name: "South East", code: "SE" },
  { id: "r3", name: "Central", code: "CN" },
];

export const mockUsers = [
  { id: "u1", email: "admin@fibre.co", name: "Alice Admin", role: "admin", lastActive: new Date(), createdAt: new Date("2024-01-01") },
  { id: "u2", email: "manager@fibre.co", name: "Bob Manager", role: "manager", lastActive: new Date(), createdAt: new Date("2024-01-15") },
  { id: "u3", email: "field@fibre.co", name: "Charlie Field", role: "field-worker", lastActive: new Date(Date.now() - 86400000), createdAt: new Date("2024-02-01") },
  { id: "u4", email: "client@example.com", name: "Dana Client", role: "client", lastActive: new Date(), createdAt: new Date("2024-03-01") },
];

export const mockStaff = [
  {
    id: "s1",
    name: "John Technician",
    email: "john@fibre.co",
    phone: "+1234567890",
    type: "employee",
    role: "Technician",
    certifications: ["Fibre Splicing"],
    skills: ["Installation", "Troubleshooting"],
    regionId: "r1",
    available: true,
    currentAssignments: ["p1"],
  },
  {
    id: "s2",
    name: "Emma Supervisor",
    email: "emma@fibre.co",
    phone: "+1234567891",
    type: "employee",
    role: "Supervisor",
    certifications: ["Heavy Equipment", "Safety"],
    skills: ["Team Lead", "Planning"],
    regionId: "r2",
    available: false,
    currentAssignments: ["p2", "p3"],
  },
  {
    id: "s3",
    name: "Mike Contractor",
    email: "mike@contractor.co",
    phone: "+1234567892",
    type: "contractor",
    role: "Technician",
    certifications: ["Trenching"],
    skills: ["Excavation"],
    regionId: "r1",
    available: true,
    currentAssignments: [],
  },
];

export const mockTeams = [
  { id: "t1", name: "Alpha Team", leadId: "s1", memberIds: ["s1", "s3"], regionId: "r1", availability: "assigned" },
  { id: "t2", name: "Bravo Team", leadId: "s2", memberIds: ["s2"], regionId: "r2", availability: "available" },
];

export const mockClients = [
  {
    id: "c1",
    name: "City Council",
    type: "government",
    contactName: "Jane Smith",
    contactEmail: "jane@city.gov",
    contactPhone: "+1111111111",
    address: "123 Main St",
    slaHours: 24,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "c2",
    name: "TechCorp Ltd",
    type: "commercial",
    contactName: "Tom Lee",
    contactEmail: "tom@techcorp.com",
    contactPhone: "+2222222222",
    address: "456 Business Rd",
    slaHours: 48,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "c3",
    name: "John Doe",
    type: "residential",
    contactName: "John Doe",
    contactEmail: "john@example.com",
    contactPhone: "+3333333333",
    address: "789 Home Ave",
    createdAt: new Date("2024-03-15"),
  },
];

export const mockProjects = [
  {
    id: "p1",
    title: "Main Street Fibre Rollout",
    clientId: "c1",
    type: "installation",
    status: "in-progress",
    address: "Main St, City",
    budget: 50000,
    startDate: new Date("2024-06-01"),
    deadline: new Date("2024-08-01"),
    assignedTeamIds: ["t1"],
    progress: 45,
    notes: "Weather delays last week.",
    attachments: [],
    materials: [],
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date(),
  },
  {
    id: "p2",
    title: "TechCorp HQ Installation",
    clientId: "c2",
    type: "installation",
    status: "planned",
    address: "456 Business Rd",
    budget: 80000,
    startDate: new Date("2024-07-01"),
    deadline: new Date("2024-09-01"),
    assignedTeamIds: [],
    progress: 0,
    notes: "",
    attachments: [],
    materials: [],
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date(),
  },
  {
    id: "p3",
    title: "Residential Connection - Doe",
    clientId: "c3",
    type: "installation",
    status: "completed",
    address: "789 Home Ave",
    budget: 5000,
    startDate: new Date("2024-04-01"),
    deadline: new Date("2024-04-15"),
    assignedTeamIds: ["t2"],
    progress: 100,
    notes: "Completed ahead of schedule.",
    attachments: [],
    materials: [],
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-04-14"),
  },
];

export const mockFaults = [
  {
    id: "f1",
    title: "Signal Loss on Main St",
    description: "Multiple residents reporting signal loss.",
    status: "open",
    priority: "high",
    reportedBy: "Jane Smith",
    reportedAt: new Date(Date.now() - 3600000),
    slaDeadline: new Date(Date.now() + 82800000),
    location: "Main St, City",
  },
  {
    id: "f2",
    title: "Cable Damage at TechCorp",
    description: "Construction crew damaged cable.",
    status: "in-progress",
    priority: "critical",
    reportedBy: "Tom Lee",
    reportedAt: new Date(Date.now() - 7200000),
    assignedTeamId: "t2",
    slaDeadline: new Date(Date.now() + 169200000),
    location: "456 Business Rd",
  },
];

export const mockDocuments = [
  {
    id: "d1",
    title: "Main St Contract",
    type: "contract",
    fileUrl: "/docs/contract1.pdf",
    uploadedBy: "u1",
    uploadedAt: new Date("2024-05-15"),
    projectId: "p1",
    tags: ["contract", "legal"],
    size: 2048000,
  },
  {
    id: "d2",
    title: "Site Plan - TechCorp",
    type: "site-plan",
    fileUrl: "/docs/siteplan2.pdf",
    uploadedBy: "u2",
    uploadedAt: new Date("2024-06-01"),
    projectId: "p2",
    tags: ["planning"],
    size: 1024000,
  },
];
